### PR TITLE
Fixed navbar to top, and added bottom border

### LINKED ISSUE #161: Make the Navigation Fixed
- Currently the navigation bar disappears once you scroll, instead it should always be fixed at the top of the screen
- Give the navigation a white background color

### LINKED ISSUE #164: Add Spacer in the Navigation Component
- Once the navigation menu is fixed, all the content will be initially behind it
- We need to implement a margin/spacer such that the content will not be hidden

### LINKED ISSUE #165: Add Navigation Bottom Border
- Add a bottom border to the navigation
- Change the color to acm-blue

### PR DESCRIPTION
**Pull request by skyguy-netizen**
closes #161 
closes #164 
closes #165

### CODE REVIEW

**Comment by skyguy-netizen** [comment]
Screenshot from 2022-09-04 11-10-36
Screenshot from 2022-09-04 11-10-04
Screenshot from 2022-09-04 11-09-57
Screenshot from 2022-09-04 11-09-48

File: components/Officers.js [hunk 1]
```diff
@@ -137,7 +137,7 @@ const colors = [
 
 const Officers = () => {
 	return (
-		<div className='container flex flex-col items-center justify-center md:p-1 sm:p-1 mx-auto'>
+		<div className='container flex flex-col items-center justify-center md:p-1 sm:p-1 mx-auto mt-[130px]'>
```
Comment (shahdivyank) [inline components/Officers.js]: Where does 130px come from?

**Review by shahdivyank — CHANGES_REQUESTED** [review]

File: components/Officers.js (hunk 1 above)
Comment (skyguy-netizen) [reply components/Officers.js]: Height of the div component that contains the navbar is around 126, so slightly more than that

**Review by shahdivyank — APPROVED** [review]

**Review by SamuelLin213 — APPROVED** [review]
